export const sampleSources = [
  {
    id: "sample-docx",
    kind: "file",
    name: "虚构项目方案.docx",
    type: "DOCX",
    size: "1.8 MB",
    description: "正常主路径 · 含文字、图片、隐藏内容和组合风险",
  },
  {
    id: "sample-xlsx",
    kind: "file",
    name: "预算汇总.xlsx",
    type: "XLSX",
    size: "860 KB",
    description: "表格主路径 · 含单位、金额区间和隐藏工作表",
  },
  {
    id: "sample-blocked",
    kind: "file",
    name: "加密资料.docx",
    type: "DOCX",
    size: "920 KB",
    blocked: true,
    blockReason: "文件已加密，无法在不解密原文件的前提下进行检查。",
    description: "阻断路径 · 可验证返回重选",
  },
  {
    id: "sample-folder",
    kind: "folder",
    name: "项目资料文件夹",
    type: "文件夹",
    size: "5 个项目",
    description: "混合队列 · 成功、失败和排除状态互不混淆",
    queue: [
      { id: "q1", name: "虚构项目方案.docx", type: "DOCX", state: "ready", stateText: "待处理" },
      { id: "q2", name: "预算汇总.xlsx", type: "XLSX", state: "ready", stateText: "待处理" },
      { id: "q3", name: "会议纪要.docx", type: "DOCX", state: "failed", stateText: "检查失败", reason: "文件结构不完整，可单独重试" },
      { id: "q4", name: "旧版材料.doc", type: "DOC", state: "excluded", stateText: "已排除", reason: "不支持旧版 Office 格式" },
      { id: "q5", name: "客户分析表.xlsx", type: "XLSX", state: "ready", stateText: "待处理" },
    ],
  },
];

export const scanStages = [
  { id: "text", label: "文字与表格", detail: "识别正文、表格和工作表中的敏感内容" },
  { id: "image", label: "图片与二维码", detail: "检查图片文字、印章、签名和二维码候选" },
  { id: "hidden", label: "隐藏内容与对象", detail: "检查属性、批注、隐藏内容、外链和嵌入对象" },
  { id: "combined", label: "组合识别风险", detail: "检查多个字段组合后是否可识别具体对象" },
];

export const initialFindings = [
  {
    id: "person",
    category: "文字",
    original: "林青河",
    suggestion: "陈顾问",
    section: "第 1 段",
    location: "正文 / 项目背景",
    occurrences: 3,
    severity: "建议替换",
    confidence: "高",
    source: "正文与表格",
    actionSet: "text",
    rule: {
      id: "standard-person-name",
      source: "standard",
      type: "判断标准",
      name: "人员姓名一致代号",
      mandatory: false,
      revision: "v3",
      matchSummary: "姓名字段或人员角色上下文",
    },
    basis: "该姓名在正文和表格中出现 3 次，建议使用同一代号以保留角色关系。",
    detail: "识别来源：本机判断标准；全部位置：正文 2 处、表格 1 处；当前任务规则快照：v3。",
  },
  {
    id: "company",
    category: "文字",
    original: "星澜科技有限公司",
    suggestion: "辰光科技有限公司",
    section: "第 3 段",
    location: "正文 / 联合单位",
    occurrences: 2,
    severity: "建议替换",
    confidence: "高",
    source: "正文与页眉",
    actionSet: "text",
    rule: {
      id: "fixed-company-alias",
      source: "fixed",
      type: "固定替换",
      name: "合作单位统一别名",
      mandatory: false,
      revision: "v2",
      matchSummary: "完整单位名称命中",
    },
    basis: "该单位名称在正文和页眉中重复出现，引用固定替换以隐藏真实主体并保持组织关系。",
    detail: "识别来源：本机固定替换；全部位置：正文 1 处、页眉 1 处；当前任务规则快照：v2。",
  },
  {
    id: "place",
    category: "文字",
    original: "云梦市",
    suggestion: "临川市",
    section: "第 4 段",
    location: "正文 / 试点位置",
    occurrences: 1,
    severity: "建议替换",
    confidence: "中",
    source: "系统识别说明",
    actionSet: "text",
    rule: {
      id: "builtin-location",
      source: "builtin",
      type: "系统识别",
      name: "地点同级替代",
      mandatory: false,
      revision: "内置",
      matchSummary: "城市名称及位置上下文",
    },
    basis: "该内容位于试点位置描述中，建议保留城市层级并替换具体地点。",
    detail: "识别来源：系统内置识别；可信程度：中；位置：正文第 4 段。",
  },
  {
    id: "seal-image",
    category: "图片",
    original: "项目确认页印章",
    suggestion: "遮住印章区域并重新编码图片",
    section: "第 2 页图片",
    location: "第 2 页 / 图片 1",
    occurrences: 1,
    severity: "必须替换",
    confidence: "高",
    source: "图片文字与印章候选",
    actionSet: "image",
    rule: {
      id: "standard-seal-image",
      source: "standard",
      type: "判断标准",
      name: "印章图像强制处理",
      mandatory: true,
      revision: "v1",
      matchSummary: "图片命中印章结构与单位文字",
    },
    basis: "图片同时包含印章轮廓和单位文字，命中你启用的强制规则。",
    detail: "识别来源：本机图片判断标准；框选区域：1；当前任务规则快照：v1。",
  },
  {
    id: "hidden-meta",
    category: "隐藏内容",
    original: "作者、修订记录与批注",
    suggestion: "移除隐藏信息并在报告中记录处理结果",
    section: "文件内部",
    location: "文件属性 / 修订记录",
    occurrences: 4,
    severity: "必须替换",
    confidence: "高",
    source: "文件结构检查",
    actionSet: "hidden",
    rule: {
      id: "builtin-hidden-content",
      source: "builtin",
      type: "系统识别",
      name: "隐藏内容安全清理",
      mandatory: true,
      revision: "内置",
      matchSummary: "文件属性、修订记录或批注存在",
    },
    basis: "这些内容不会出现在普通正文中，但可能保留作者和修改痕迹，需在副本中移除。",
    detail: "识别来源：OOXML 结构检查；包含作者 1 项、修订记录 2 项、批注 1 项。",
  },
  {
    id: "combined-risk",
    category: "组合风险",
    original: "人员姓名 + 精确地点 + 设备编号",
    suggestion: "保留人员代号，降低地点精度并替换设备编号",
    section: "跨段组合",
    location: "第 1、4 段与附表",
    occurrences: 3,
    severity: "需要你判断",
    confidence: "中",
    source: "组合风险检查",
    actionSet: "combined",
    rule: {
      id: "standard-combined-risk",
      source: "standard",
      type: "判断标准",
      name: "人员与设备组合识别风险",
      mandatory: true,
      revision: "v2",
      matchSummary: "人员、精确地点和设备编号共同出现",
    },
    basis: "姓名、设备编号和精确地点共同出现，组合后可能识别具体人员，需要单独确认。",
    detail: "贡献字段：人员姓名、楼栋位置、设备编号；建议优先模糊地点并替换设备编号。",
  },
];

export const initialRules = [
  {
    id: "fixed-company-alias",
    type: "fixed",
    name: "合作单位统一别名",
    matchMode: "等于",
    pattern: "星澜科技有限公司",
    action: "换成固定代号",
    replacement: "辰光科技有限公司",
    scope: "正文、页眉页脚",
    mandatory: false,
    enabled: true,
    updatedAt: "今天 09:30",
    builtIn: false,
  },
  {
    id: "fixed-system-code",
    type: "fixed",
    name: "内部系统统一代号",
    matchMode: "包含",
    pattern: "星桥协同系统",
    action: "换成固定代号",
    replacement: "系统 A",
    scope: "正文、表格",
    mandatory: true,
    enabled: true,
    updatedAt: "昨天 16:20",
    builtIn: false,
  },
  {
    id: "standard-person-name",
    type: "standard",
    name: "人员姓名一致代号",
    matchMode: "符合格式",
    pattern: "姓名字段或人员角色上下文",
    action: "生成顺序代号",
    replacement: "人员代号",
    scope: "正文、表格、图片 OCR",
    mandatory: false,
    enabled: true,
    updatedAt: "今天 08:45",
    positiveExample: "项目负责人：林青河",
    negativeExample: "青河路",
    builtIn: false,
  },
  {
    id: "standard-seal-image",
    type: "standard",
    name: "印章图像强制处理",
    matchMode: "同时包含全部关键词",
    pattern: "印章轮廓、单位文字",
    action: "遮住敏感区域",
    replacement: "像素处理",
    scope: "图片 OCR",
    mandatory: true,
    enabled: true,
    updatedAt: "8 月 8 日",
    positiveExample: "圆形印章 + 单位全称",
    negativeExample: "普通红色图标",
    builtIn: false,
  },
  {
    id: "standard-combined-risk",
    type: "standard",
    name: "人员与设备组合识别风险",
    matchMode: "同时包含全部关键词",
    pattern: "人员、精确地点、设备编号",
    action: "仅人工判断",
    replacement: "逐项确认",
    scope: "正文、表格",
    mandatory: true,
    enabled: true,
    updatedAt: "8 月 7 日",
    positiveExample: "张顾问 + A 栋 302 + DEV-001",
    negativeExample: "某人员 + 某园区",
    builtIn: false,
  },
];

export const builtinRuleExplanations = [
  { id: "builtin-name", category: "姓名", standard: "姓名字段或人员角色上下文", treatment: "一致代号", example: "负责人：陈顾问" },
  { id: "builtin-phone", category: "手机号", standard: "11 位号码且位于联系方式上下文", treatment: "保留首尾并加星号", example: "138****5678" },
  { id: "builtin-location", category: "地点", standard: "城市、区县、园区或楼栋位置上下文", treatment: "同级替代或降低精度", example: "临川市 / 某园区" },
  { id: "builtin-hidden-content", category: "隐藏内容", standard: "文件属性、修订、批注、隐藏对象", treatment: "移除并记录", example: "已移除 4 项" },
];

export const initialHistory = [
  { id: "history-budget", name: "预算汇总.xlsx", type: "XLSX", status: "已完成", tone: "success", time: "今天 10:32", summary: "处理 8 项 · 结果可用", resultAvailable: true, group: "today" },
  { id: "history-minutes", name: "会议纪要.docx", type: "DOCX", status: "已失败", tone: "error", time: "今天 09:18", summary: "文件结构不完整", resultAvailable: false, group: "today" },
  { id: "history-analysis", name: "客户分析表.xlsx", type: "XLSX", status: "已完成", tone: "success", time: "8 月 8 日", summary: "处理 5 项 · 结果可用", resultAvailable: true, group: "earlier" },
  { id: "history-draft", name: "合作计划.docx", type: "DOCX", status: "待确认 2 项", tone: "warning", time: "8 月 7 日", summary: "可继续处理", resultAvailable: false, group: "earlier" },
];

export const outputFiles = {
  ai: [{ id: "ai-copy", name: "AI分析副本.docx", note: "保留版式结构，仅包含已确认的替代内容" }],
  local: [
    { id: "mapping", name: "脱敏映射表.xlsx", note: "含真实原值，仅限本地保管，严禁上传", danger: true },
    { id: "report", name: "脱敏检查报告.html", note: "记录技术检查范围、处理数量和结果" },
  ],
};

export function createPrototypeId(prefix = "item") {
  return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2, 7)}`;
}
